version: '3.1'

services:
  rest:
    build: .
    image: inkscape-converter-microservice
    ports:
      - "8080:8080"
    environment:
      # if no specific directories are defined, subdirectories in the data directory will be used
      - DATA_DIRECTORY=/data
      #- DATABASE_DIRECTORY=/data/database
      #- CONVERSIONS_DIRECTORY=/data/conversions