version: '3.1'

services:
  rest:
    build: .
    image: inkscape-converter-microservice
    ports:
      - "8080:8080"
    environment:
      - DATABASE_DIRECTORY=/data/database
      - CONVERSIONS_DIRECTORY=/data/conversions