components:
  schemas:
    ConversionIn:
      properties:
        base64:
          title: Base64
          type: string
        inputformat:
          title: Inputformat
          type: string
        outputformat:
          title: Outputformat
          type: string
      required:
      - base64
      - inputformat
      - outputformat
      title: ConversionIn
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /health:
    get:
      operationId: get_health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Health
  /health_async:
    get:
      operationId: get_health_async_health_async_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Health Async
  /images/:
    post:
      operationId: convert_image_images__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversionIn'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Convert Image
