components:
  schemas:
    ConversionRequest:
      properties:
        base64:
          title: Base64
          type: string
        inputFormat:
          title: Inputformat
          type: string
        outputFormat:
          title: Outputformat
          type: string
      required:
      - base64
      - inputFormat
      - outputFormat
      title: ConversionRequest
      type: object
    ConversionResponse:
      properties:
        createdOn:
          title: Createdon
          type: string
        id:
          title: Id
          type: string
        inputFormat:
          title: Inputformat
          type: string
        outputFormat:
          title: Outputformat
          type: string
      required:
      - id
      - inputFormat
      - outputFormat
      - createdOn
      title: ConversionResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /health:
    get:
      operationId: get_health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Health
  /health_async:
    get:
      operationId: get_health_async_health_async_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Health Async
  /images/:
    get:
      operationId: get_images_images__get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConversionResponse'
                title: Response Get Images Images  Get
                type: array
          description: Successful Response
      summary: Get Images
    post:
      operationId: post_image_images__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversionRequest'
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Post Image
  /images/{image_id}:
    delete:
      operationId: delete_image_images__image_id__delete
      parameters:
      - in: path
        name: image_id
        required: true
        schema:
          title: Image Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Image
    get:
      operationId: get_image_images__image_id__get
      parameters:
      - in: path
        name: image_id
        required: true
        schema:
          title: Image Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Image
  /images/{image_id}/download:
    get:
      operationId: download_image_images__image_id__download_get
      parameters:
      - in: path
        name: image_id
        required: true
        schema:
          title: Image Id
          type: string
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Download Image
